name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare docker-compose.yaml
        run: |
          cat << EOF > docker-compose.yaml
            version: "3.8"
            services:
              app:
                environment:
                  MAINTAINER: "${{ vars.MAINTAINER }}"
                  SLACK_TOKEN: "${{ secrets.SLACK_TOKEN }}"
                  SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
                build:
                  context: .
                  dockerfile: Dockerfile
                  args:
                    GIT_USER_NAME: "${{ vars.GIT_USER_NAME }}"
                    GIT_USER_EMAIL: "${{ secrets.GIT_USER_EMAIL }}"
                    AUR_SSH_PRIV_KEY: "${{ secrets.AUR_SSH_PRIV_KEY }}"
                image: local/update-pkgbuild-on-aur:latest
                restart: always
                network_mode: bridge
          EOF
        shell: bash
      - name: Prepare containers
        run: docker compose build
      - name: Run containers
        run: docker compose up
